/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;


import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
 
/**
 *
 * @author fermat
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setTitle("Photo By Fermat");
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabelFoto1 = new javax.swing.JLabel();
        jLabelFotoFinal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        TonoGris1 = new javax.swing.JMenuItem();
        TonoGris2 = new javax.swing.JMenuItem();
        TonoGris3 = new javax.swing.JMenuItem();
        TonoGris4 = new javax.swing.JMenuItem();
        TonoGris5 = new javax.swing.JMenuItem();
        TonoGris6 = new javax.swing.JMenuItem();
        TonoGris7 = new javax.swing.JMenuItem();
        TonoGris8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFoto1.setText("Foto Cargada");

        jLabelFotoFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFotoFinal.setText("Foto  final");

        jMenu1.setText("Imagen");

        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        jMenu1.add(Abrir);

        Guardar.setText("Guardar");
        jMenu1.add(Guardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Filtros");

        jMenuItem7.setText("Inverso");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem6.setText("Alto Contraste");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenu6.setText("Tonos Grises");

        TonoGris1.setText("Promedio");
        TonoGris1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TonoGris1ActionPerformed(evt);
            }
        });
        jMenu6.add(TonoGris1);

        TonoGris2.setText("Por valores");
        TonoGris2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TonoGris2ActionPerformed(evt);
            }
        });
        jMenu6.add(TonoGris2);

        TonoGris3.setText("Desaturación");
        TonoGris3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TonoGris3ActionPerformed(evt);
            }
        });
        jMenu6.add(TonoGris3);

        TonoGris4.setText("Máx");
        TonoGris4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TonoGris4ActionPerformed(evt);
            }
        });
        jMenu6.add(TonoGris4);

        TonoGris5.setText("Mín");
        TonoGris5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TonoGris5ActionPerformed(evt);
            }
        });
        jMenu6.add(TonoGris5);

        TonoGris6.setText("Rojo");
        TonoGris6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TonoGris6ActionPerformed(evt);
            }
        });
        jMenu6.add(TonoGris6);

        TonoGris7.setText("Verde");
        TonoGris7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TonoGris7ActionPerformed(evt);
            }
        });
        jMenu6.add(TonoGris7);

        TonoGris8.setText("Azul");
        TonoGris8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TonoGris8ActionPerformed(evt);
            }
        });
        jMenu6.add(TonoGris8);

        jMenu2.add(jMenu6);

        jMenuItem2.setText("Brillo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem8.setText("Mosaico");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Acerca de ");

        jMenuItem3.setText("Derechos Reservados by Fermat");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("jMenu4");

        jMenuItem4.setText("jMenuItem4");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFotoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFoto1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(jLabelFotoFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    File fichero;
    
    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        int resultado;
        CargarImagen ventana=new CargarImagen();
        FileNameExtensionFilter filtro= new FileNameExtensionFilter("JPG","jpg","PNG","png");
        ventana.CargarFoto.setFileFilter(filtro);
        resultado = ventana.CargarFoto.showOpenDialog(null);
        
        if(JFileChooser.APPROVE_OPTION == resultado)
        {
        fichero=ventana.CargarFoto.getSelectedFile();
        System.out.println(fichero+ " Hola");
            try{
                 
                ImageIcon icon= new ImageIcon(fichero.toString());
                Icon icono=new ImageIcon(icon.getImage().getScaledInstance(jLabelFoto1.getWidth(),jLabelFoto1.getHeight(),Image.SCALE_DEFAULT));
                
                jLabelFoto1.setText(null);
                jLabelFoto1.setIcon(icono);
                
            }catch (Exception ex){
                
                
            JOptionPane.showMessageDialog(null,"Error al abrir imagen" + ex );
            }   
            
            
        }
        
        
    }//GEN-LAST:event_AbrirActionPerformed
    
    
    
    
    private void TonoGris3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TonoGris3ActionPerformed
        FiltroGrises ObjProcesamiento =new FiltroGrises();
        ObjProcesamiento.abrirImagen(fichero);
        BufferedImage ImaPro = ObjProcesamiento.grisDeSaturacion();
        ImageIcon icon= new ImageIcon(ImaPro);
        Icon icono=new ImageIcon(icon.getImage().getScaledInstance(jLabelFotoFinal.getWidth(),jLabelFotoFinal.getHeight(),Image.SCALE_DEFAULT));   
        jLabelFotoFinal.setText(null);       
        jLabelFotoFinal.setIcon(icono);
        
    }//GEN-LAST:event_TonoGris3ActionPerformed

    private void TonoGris1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TonoGris1ActionPerformed
        FiltroGrises ObjProcesamiento =new FiltroGrises();
        ObjProcesamiento.abrirImagen(fichero);
        BufferedImage ImaPro = ObjProcesamiento.GrisPromedio();
        ImageIcon icon= new ImageIcon(ImaPro);
        Icon icono=new ImageIcon(icon.getImage().getScaledInstance(jLabelFotoFinal.getWidth(),jLabelFotoFinal.getHeight(),Image.SCALE_DEFAULT));   
        jLabelFotoFinal.setText(null);       
        jLabelFotoFinal.setIcon(icono);
        
    }//GEN-LAST:event_TonoGris1ActionPerformed

    private void TonoGris2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TonoGris2ActionPerformed
        FiltroGrises ObjProcesamiento =new FiltroGrises();
        ObjProcesamiento.abrirImagen(fichero);
        BufferedImage ImaPro = ObjProcesamiento.grisValor();
        ImageIcon icon= new ImageIcon(ImaPro);
        Icon icono=new ImageIcon(icon.getImage().getScaledInstance(jLabelFotoFinal.getWidth(),jLabelFotoFinal.getHeight(),Image.SCALE_DEFAULT));   
        jLabelFotoFinal.setText(null);       
        jLabelFotoFinal.setIcon(icono);
    }//GEN-LAST:event_TonoGris2ActionPerformed

    private void TonoGris6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TonoGris6ActionPerformed
        FiltroGrises ObjProcesamiento =new FiltroGrises();
        ObjProcesamiento.abrirImagen(fichero);
        BufferedImage ImaPro = ObjProcesamiento.grisPorColor(0);
        ImageIcon icon= new ImageIcon(ImaPro);
        Icon icono=new ImageIcon(icon.getImage().getScaledInstance(jLabelFotoFinal.getWidth(),jLabelFotoFinal.getHeight(),Image.SCALE_DEFAULT));   
        jLabelFotoFinal.setText(null);       
        jLabelFotoFinal.setIcon(icono);
    }//GEN-LAST:event_TonoGris6ActionPerformed

    private void TonoGris4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TonoGris4ActionPerformed
         FiltroGrises ObjProcesamiento =new FiltroGrises();
        ObjProcesamiento.abrirImagen(fichero);
        BufferedImage ImaPro = ObjProcesamiento.grisDescomposicion(true);
        ImageIcon icon= new ImageIcon(ImaPro);
        Icon icono=new ImageIcon(icon.getImage().getScaledInstance(jLabelFotoFinal.getWidth(),jLabelFotoFinal.getHeight(),Image.SCALE_DEFAULT));   
        jLabelFotoFinal.setText(null);       
        jLabelFotoFinal.setIcon(icono);
    }//GEN-LAST:event_TonoGris4ActionPerformed

    private void TonoGris5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TonoGris5ActionPerformed
        FiltroGrises ObjProcesamiento =new FiltroGrises();
        ObjProcesamiento.abrirImagen(fichero);
        BufferedImage ImaPro = ObjProcesamiento.grisDescomposicion(false);
        ImageIcon icon= new ImageIcon(ImaPro);
        Icon icono=new ImageIcon(icon.getImage().getScaledInstance(jLabelFotoFinal.getWidth(),jLabelFotoFinal.getHeight(),Image.SCALE_DEFAULT));   
        jLabelFotoFinal.setText(null);       
        jLabelFotoFinal.setIcon(icono);// TODO add your handling code here:
    }//GEN-LAST:event_TonoGris5ActionPerformed

    private void TonoGris7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TonoGris7ActionPerformed
        FiltroGrises ObjProcesamiento =new FiltroGrises();
        ObjProcesamiento.abrirImagen(fichero);
        BufferedImage ImaPro = ObjProcesamiento.grisPorColor(2);
        ImageIcon icon= new ImageIcon(ImaPro);
        Icon icono=new ImageIcon(icon.getImage().getScaledInstance(jLabelFotoFinal.getWidth(),jLabelFotoFinal.getHeight(),Image.SCALE_DEFAULT));   
        jLabelFotoFinal.setText(null);       
        jLabelFotoFinal.setIcon(icono);
    }//GEN-LAST:event_TonoGris7ActionPerformed

    private void TonoGris8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TonoGris8ActionPerformed
        FiltroGrises ObjProcesamiento =new FiltroGrises();
        ObjProcesamiento.abrirImagen(fichero);
        BufferedImage ImaPro = ObjProcesamiento.grisPorColor(3);
        ImageIcon icon= new ImageIcon(ImaPro);
        Icon icono=new ImageIcon(icon.getImage().getScaledInstance(jLabelFotoFinal.getWidth(),jLabelFotoFinal.getHeight(),Image.SCALE_DEFAULT));   
        jLabelFotoFinal.setText(null);       
        jLabelFotoFinal.setIcon(icono);
    }//GEN-LAST:event_TonoGris8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       FiltroInversoAltoContraste ObjProcesamiento =new FiltroInversoAltoContraste();
        ObjProcesamiento.abrirImagen(fichero);
        BufferedImage ImaPro = ObjProcesamiento.Inverso();
        ImageIcon icon= new ImageIcon(ImaPro);
        Icon icono=new ImageIcon(icon.getImage().getScaledInstance(jLabelFotoFinal.getWidth(),jLabelFotoFinal.getHeight(),Image.SCALE_DEFAULT));   
        jLabelFotoFinal.setText(null);       
        jLabelFotoFinal.setIcon(icono);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        
        FiltroInversoAltoContraste ObjProcesamiento =new FiltroInversoAltoContraste();
        ObjProcesamiento.abrirImagen(fichero);
        BufferedImage ImaPro = ObjProcesamiento.AltoContraste();
        ImageIcon icon= new ImageIcon(ImaPro);
        Icon icono=new ImageIcon(icon.getImage().getScaledInstance(jLabelFotoFinal.getWidth(),jLabelFotoFinal.getHeight(),Image.SCALE_DEFAULT));   
        jLabelFotoFinal.setText(null);       
        jLabelFotoFinal.setIcon(icono);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        NivelBrillo ventanaNivel =new NivelBrillo();
        ventanaNivel.abrirImagen(fichero);
        ventanaNivel.setVisible(true);
         
              
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
         NumMosaico ventanaNivel =new NumMosaico();
        ventanaNivel.abrirImagen(fichero);
        ventanaNivel.setVisible(true);
      
       
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenuItem TonoGris1;
    private javax.swing.JMenuItem TonoGris2;
    private javax.swing.JMenuItem TonoGris3;
    private javax.swing.JMenuItem TonoGris4;
    private javax.swing.JMenuItem TonoGris5;
    private javax.swing.JMenuItem TonoGris6;
    private javax.swing.JMenuItem TonoGris7;
    private javax.swing.JMenuItem TonoGris8;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabelFoto1;
    public static javax.swing.JLabel jLabelFotoFinal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
